// AUTO-GENERATED by tools/gen-standalone.mjs — do not edit by hand.
//
// Every provider the Nango emulator can proxy is ALSO shipped here as a
// standalone emulator that serves the provider's OWN native REST surface
// behind its own bearer token — no Nango connection/records/proxy layer.
// Nango stays one option; "go direct to source" is always the other.
import type { ServiceEntry } from "emulate";

export const DIRECT_REGISTRY: Record<string, ServiceEntry> = {
  xero: {
    label: "xero direct-to-source emulator (native REST, no proxy)",
    endpoints: "Direct Xero Accounting — OAuth2, tenants, stateful Invoices, and Xero's own signed `events[]` webhook.",
    async load() {
      const m = await import("@emulators/xero");
      return { plugin: m.xeroPlugin };
    },
    defaultFallback() {
      return { login: "xero-emulator", id: 1, scopes: [] };
    },
    initConfig: { xero: {} },
  },
  quickbooks: {
    label: "quickbooks direct-to-source emulator (native REST, no proxy)",
    endpoints:
      "Direct QuickBooks Online — OAuth2, stateful invoices, SQL-ish query, and QuickBooks' own signed `eventNotifications[]` webhook.",
    async load() {
      const m = await import("@emulators/quickbooks");
      return { plugin: m.quickbooksPlugin };
    },
    defaultFallback() {
      return { login: "quickbooks-emulator", id: 1, scopes: [] };
    },
    initConfig: { quickbooks: {} },
  },
  salesforce: {
    label: "salesforce direct-to-source emulator (native REST, no proxy)",
    endpoints:
      "Direct Salesforce — OAuth2 (password/code/refresh), sObjects CRUD, SOQL query, composite create, describe.",
    async load() {
      const m = await import("@emulators/salesforce");
      return { plugin: m.salesforcePlugin };
    },
    defaultFallback() {
      return { login: "salesforce-emulator", id: 1, scopes: [] };
    },
    initConfig: { salesforce: {} },
  },
  hubspot: {
    label: "hubspot direct-to-source emulator (native REST, no proxy)",
    endpoints:
      "Direct HubSpot — OAuth2 + token introspection and the CRM v3/v4 object API (CRUD, search, batch, associations).",
    async load() {
      const m = await import("@emulators/hubspot");
      return { plugin: m.hubspotPlugin };
    },
    defaultFallback() {
      return { login: "hubspot-emulator", id: 1, scopes: [] };
    },
    initConfig: { hubspot: {} },
  },
  pipedrive: {
    label: "pipedrive direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Person /v1/persons, Deal /v1/deals",
    async load() {
      const m = await import("@emulators/pipedrive");
      return { plugin: m.pipedrivePlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "pipedrive-emulator", id: 1, scopes: [] };
    },
    initConfig: { pipedrive: {} },
  },
  "zoho-crm": {
    label: "zoho-crm direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/v2/token) + native collections: Leads /crm/v3/Leads",
    async load() {
      const m = await import("@emulators/zoho-crm");
      return { plugin: m.zohoCrmPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "zoho-crm-emulator", id: 1, scopes: [] };
    },
    initConfig: { "zoho-crm": {} },
  },
  freshbooks: {
    label: "freshbooks direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Invoice /accounting/account/ACME/invoices/invoices",
    async load() {
      const m = await import("@emulators/freshbooks");
      return { plugin: m.freshbooksPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "freshbooks-emulator", id: 1, scopes: [] };
    },
    initConfig: { freshbooks: {} },
  },
  "wave-accounting": {
    label: "wave-accounting direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Invoice /invoices",
    async load() {
      const m = await import("@emulators/wave-accounting");
      return {
        plugin: m.waveAccountingPlugin,
        seedFromConfig: m.seedFromConfig,
        storeToSeedConfig: m.storeToSeedConfig,
      };
    },
    defaultFallback() {
      return { login: "wave-accounting-emulator", id: 1, scopes: [] };
    },
    initConfig: { "wave-accounting": {} },
  },
  discord: {
    label: "discord direct-to-source emulator (native REST, no proxy)",
    endpoints:
      "OAuth2 token (/oauth/token) + native collections: Channel /api/v10/channels, Message /api/v10/channels/CHANNEL/messages",
    async load() {
      const m = await import("@emulators/discord");
      return { plugin: m.discordPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "discord-emulator", id: 1, scopes: [] };
    },
    initConfig: { discord: {} },
  },
  mailchimp: {
    label: "mailchimp direct-to-source emulator (native REST, no proxy)",
    endpoints:
      "OAuth2 token (/oauth/token) + native collections: Member /3.0/lists/LIST/members, Campaign /3.0/campaigns",
    async load() {
      const m = await import("@emulators/mailchimp");
      return { plugin: m.mailchimpPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "mailchimp-emulator", id: 1, scopes: [] };
    },
    initConfig: { mailchimp: {} },
  },
  sendgrid: {
    label: "sendgrid direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Contact /v3/marketing/contacts",
    async load() {
      const m = await import("@emulators/sendgrid");
      return { plugin: m.sendgridPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "sendgrid-emulator", id: 1, scopes: [] };
    },
    initConfig: { sendgrid: {} },
  },
  klaviyo: {
    label: "klaviyo direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Profile /api/profiles",
    async load() {
      const m = await import("@emulators/klaviyo");
      return { plugin: m.klaviyoPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "klaviyo-emulator", id: 1, scopes: [] };
    },
    initConfig: { klaviyo: {} },
  },
  dropbox: {
    label: "dropbox direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: File /2/files",
    async load() {
      const m = await import("@emulators/dropbox");
      return { plugin: m.dropboxPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "dropbox-emulator", id: 1, scopes: [] };
    },
    initConfig: { dropbox: {} },
  },
  box: {
    label: "box direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: File /2.0/files",
    async load() {
      const m = await import("@emulators/box");
      return { plugin: m.boxPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "box-emulator", id: 1, scopes: [] };
    },
    initConfig: { box: {} },
  },
  jira: {
    label: "jira direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Issue /rest/api/3/issue, Project /rest/api/3/project",
    async load() {
      const m = await import("@emulators/jira");
      return { plugin: m.jiraPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "jira-emulator", id: 1, scopes: [] };
    },
    initConfig: { jira: {} },
  },
  linear: {
    label: "linear direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Issue /issues",
    async load() {
      const m = await import("@emulators/linear");
      return { plugin: m.linearPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "linear-emulator", id: 1, scopes: [] };
    },
    initConfig: { linear: {} },
  },
  asana: {
    label: "asana direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Task /api/1.0/tasks",
    async load() {
      const m = await import("@emulators/asana");
      return { plugin: m.asanaPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "asana-emulator", id: 1, scopes: [] };
    },
    initConfig: { asana: {} },
  },
  notion: {
    label: "notion direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Page /v1/pages, Database /v1/databases",
    async load() {
      const m = await import("@emulators/notion");
      return { plugin: m.notionPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "notion-emulator", id: 1, scopes: [] };
    },
    initConfig: { notion: {} },
  },
  clickup: {
    label: "clickup direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Task /api/v2/task",
    async load() {
      const m = await import("@emulators/clickup");
      return { plugin: m.clickupPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "clickup-emulator", id: 1, scopes: [] };
    },
    initConfig: { clickup: {} },
  },
  monday: {
    label: "monday direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Item /items",
    async load() {
      const m = await import("@emulators/monday");
      return { plugin: m.mondayPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "monday-emulator", id: 1, scopes: [] };
    },
    initConfig: { monday: {} },
  },
  trello: {
    label: "trello direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Card /1/cards, Board /1/boards",
    async load() {
      const m = await import("@emulators/trello");
      return { plugin: m.trelloPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "trello-emulator", id: 1, scopes: [] };
    },
    initConfig: { trello: {} },
  },
  gitlab: {
    label: "gitlab direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Project /api/v4/projects, Issue /api/v4/issues",
    async load() {
      const m = await import("@emulators/gitlab");
      return { plugin: m.gitlabPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "gitlab-emulator", id: 1, scopes: [] };
    },
    initConfig: { gitlab: {} },
  },
  zendesk: {
    label: "zendesk direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Ticket /api/v2/tickets, User /api/v2/users",
    async load() {
      const m = await import("@emulators/zendesk");
      return { plugin: m.zendeskPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "zendesk-emulator", id: 1, scopes: [] };
    },
    initConfig: { zendesk: {} },
  },
  intercom: {
    label: "intercom direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Contact /contacts, Conversation /conversations",
    async load() {
      const m = await import("@emulators/intercom");
      return { plugin: m.intercomPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "intercom-emulator", id: 1, scopes: [] };
    },
    initConfig: { intercom: {} },
  },
  bamboohr: {
    label: "bamboohr direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Employee /api/v1/employees",
    async load() {
      const m = await import("@emulators/bamboohr");
      return { plugin: m.bamboohrPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "bamboohr-emulator", id: 1, scopes: [] };
    },
    initConfig: { bamboohr: {} },
  },
  greenhouse: {
    label: "greenhouse direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Candidate /v1/candidates, Job /v1/jobs",
    async load() {
      const m = await import("@emulators/greenhouse");
      return { plugin: m.greenhousePlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "greenhouse-emulator", id: 1, scopes: [] };
    },
    initConfig: { greenhouse: {} },
  },
  lever: {
    label: "lever direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Opportunity /v1/opportunities",
    async load() {
      const m = await import("@emulators/lever");
      return { plugin: m.leverPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "lever-emulator", id: 1, scopes: [] };
    },
    initConfig: { lever: {} },
  },
  shopify: {
    label: "shopify direct-to-source emulator (native REST, no proxy)",
    endpoints:
      "OAuth2 token (/admin/oauth/access_token) + native collections: Product /admin/api/2024-01/products, Order /admin/api/2024-01/orders",
    async load() {
      const m = await import("@emulators/shopify");
      return { plugin: m.shopifyPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "shopify-emulator", id: 1, scopes: [] };
    },
    initConfig: { shopify: {} },
  },
  mixpanel: {
    label: "mixpanel direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Event /api/2.0/events",
    async load() {
      const m = await import("@emulators/mixpanel");
      return { plugin: m.mixpanelPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "mixpanel-emulator", id: 1, scopes: [] };
    },
    initConfig: { mixpanel: {} },
  },
  typeform: {
    label: "typeform direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Form /forms, Response /forms/FORM/responses",
    async load() {
      const m = await import("@emulators/typeform");
      return { plugin: m.typeformPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "typeform-emulator", id: 1, scopes: [] };
    },
    initConfig: { typeform: {} },
  },
  airtable: {
    label: "airtable direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: Record /v0/BASE/Records",
    async load() {
      const m = await import("@emulators/airtable");
      return { plugin: m.airtablePlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "airtable-emulator", id: 1, scopes: [] };
    },
    initConfig: { airtable: {} },
  },
  calendly: {
    label: "calendly direct-to-source emulator (native REST, no proxy)",
    endpoints: "OAuth2 token (/oauth/token) + native collections: ScheduledEvent /scheduled_events",
    async load() {
      const m = await import("@emulators/calendly");
      return { plugin: m.calendlyPlugin, seedFromConfig: m.seedFromConfig, storeToSeedConfig: m.storeToSeedConfig };
    },
    defaultFallback() {
      return { login: "calendly-emulator", id: 1, scopes: [] };
    },
    initConfig: { calendly: {} },
  },
};

export const DIRECT_NAMES = [
  "xero",
  "quickbooks",
  "salesforce",
  "hubspot",
  "pipedrive",
  "zoho-crm",
  "freshbooks",
  "wave-accounting",
  "discord",
  "mailchimp",
  "sendgrid",
  "klaviyo",
  "dropbox",
  "box",
  "jira",
  "linear",
  "asana",
  "notion",
  "clickup",
  "monday",
  "trello",
  "gitlab",
  "zendesk",
  "intercom",
  "bamboohr",
  "greenhouse",
  "lever",
  "shopify",
  "mixpanel",
  "typeform",
  "airtable",
  "calendly",
] as const;
