import { describe, it, expect } from "vitest";
import { Hono } from "hono";
import { Store, WebhookDispatcher } from "@emulators/core";
import { boxPlugin, seedFromConfig, storeToSeedConfig } from "../index.js";
import { spec } from "../spec.js";

// Auto-generated by tools/gen-standalone.mjs — proves the seed-derived native
// surface: default seed serves rows at the provider's real collection path,
// bearer is enforced, and the store round-trips through storeToSeedConfig.
const base = "http://localhost:4000";

function mk() {
  const store = new Store();
  const app = new Hono();
  boxPlugin.register(app as never, store, new WebhookDispatcher(), base);
  return { app, store };
}

// The row array lives under a dialect-specific key (`data` for the default
// envelope, `issues`/`tickets`/`products` for Jira/Zendesk/Shopify): take
// the first array value so the assertion is dialect-agnostic.
const rowsOf = (body: Record<string, unknown>): unknown[] =>
  (Object.values(body).find(Array.isArray) as unknown[] | undefined) ?? [];

describe("box standalone native (native-kit, seed-derived)", () => {
  for (const model of spec.models) {
    it(`serves seeded ${model.model} at ${model.collectionPath}`, async () => {
      const { app, store } = mk();
      boxPlugin.seed?.(store, base);
      const r = await app.request(`${base}${model.collectionPath}`, {
        headers: { Authorization: "Bearer x" },
      });
      expect(r.status).toBe(200);
      const body = (await r.json()) as Record<string, unknown>;
      expect(rowsOf(body).length).toBe(model.rows.length);
    });
  }

  it("rejects unauthenticated reads", async () => {
    const { app } = mk();
    const r = await app.request(`${base}${spec.models[0].collectionPath}`);
    expect(r.status).toBe(401);
  });

  it("storeToSeedConfig round-trips the live store", async () => {
    const { app, store } = mk();
    boxPlugin.seed?.(store, base);
    const m0 = spec.models[0];
    await app.request(`${base}${m0.collectionPath}`, {
      method: "POST",
      headers: { Authorization: "Bearer x", "Content-Type": "application/json" },
      body: JSON.stringify({ _smoke: true }),
    });
    const exported = storeToSeedConfig(store, base);
    expect((exported.records?.[m0.model] ?? []).length).toBe(m0.rows.length + 1);

    const fresh = mk();
    seedFromConfig(fresh.store, base, exported);
    const rr = await fresh.app.request(`${base}${m0.collectionPath}`, {
      headers: { Authorization: "Bearer x" },
    });
    const reread = (await rr.json()) as Record<string, unknown>;
    expect(rowsOf(reread).length).toBe(m0.rows.length + 1);
  });
});
