import { describe, it, expect } from "vitest";
import { Hono } from "hono";
import { Store, WebhookDispatcher } from "@emulators/core";
import { greenhousePlugin, seedFromConfig, storeToSeedConfig } from "../index.js";
import { spec } from "../spec.js";

// Auto-generated by tools/gen-standalone.mjs — proves the seed-derived native
// surface: default seed serves rows at the provider's real collection path,
// bearer is enforced, and the store round-trips through storeToSeedConfig.
const base = "http://localhost:4000";

function mk() {
  const store = new Store();
  const app = new Hono();
  greenhousePlugin.register(app as never, store, new WebhookDispatcher(), base);
  return { app, store };
}

describe("greenhouse standalone native (native-kit, seed-derived)", () => {
  for (const model of spec.models) {
    it(`serves seeded ${model.model} at ${model.collectionPath}`, async () => {
      const { app, store } = mk();
      greenhousePlugin.seed?.(store, base);
      const r = await app.request(`${base}${model.collectionPath}`, {
        headers: { Authorization: "Bearer x" },
      });
      expect(r.status).toBe(200);
      const body = (await r.json()) as { data: unknown[]; total: number; model: string };
      expect(body.model).toBe(model.model);
      expect(body.total).toBe(model.rows.length);
    });
  }

  it("rejects unauthenticated reads", async () => {
    const { app } = mk();
    const r = await app.request(`${base}${spec.models[0].collectionPath}`);
    expect(r.status).toBe(401);
  });

  it("storeToSeedConfig round-trips the live store", async () => {
    const { app, store } = mk();
    greenhousePlugin.seed?.(store, base);
    const m0 = spec.models[0];
    await app.request(`${base}${m0.collectionPath}`, {
      method: "POST",
      headers: { Authorization: "Bearer x", "Content-Type": "application/json" },
      body: JSON.stringify({ _smoke: true }),
    });
    const exported = storeToSeedConfig(store, base);
    expect((exported.records?.[m0.model] ?? []).length).toBe(m0.rows.length + 1);

    const fresh = mk();
    seedFromConfig(fresh.store, base, exported);
    const rr = await fresh.app.request(`${base}${m0.collectionPath}`, {
      headers: { Authorization: "Bearer x" },
    });
    const reread = (await rr.json()) as { total: number };
    expect(reread.total).toBe(m0.rows.length + 1);
  });
});
